### ISSUE TITLE
How to push view controller ,after the animation.

### ISSUE THREAD

**Issue by bharathi91** [jonathantribouharet/JTHamburgerButton#1]
Here is my code:
- (IBAction)btn2act:(JTHamburgerButton *)sender
  {
  if(sender.currentMode == JTHamburgerButtonModeHamburger){
      [sender setCurrentModeWithAnimation:JTHamburgerButtonModeCross];
  }
  else{
      [sender setCurrentModeWithAnimation:JTHamburgerButtonModeHamburger];
  }
  mapViewController *map=[[mapViewController alloc]init];
  [self.navigationController pushViewController:map animated:YES];
  }

Im not able to push view controller.

**Comment by johnvuko** [comment]
There is no callback for the animation because I use 3 different animations (one for each layer).
If you want to have the callback for when the animation is finished, you can do something like that (not tested):

```
[CATransaction begin];
[sender setCurrentModeWithAnimation:JTHamburgerButtonModeHamburger];
[CATransaction setCompletionBlock:^{
    MapViewController *map= [MapViewController new];
    [self.navigationController pushViewController:map animated:YES];
}];
[CATransaction commit];
```

But it's not a good user experience (in my opinion), you shouldn't wait the end of the animation of the button for start the transition between the controllers.
In my app I created my own navigation controller (for others reasons) and I managed the transition myself, but I think you can try to just override the default navigationBar instead or the navigation controller.
